const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.join(__dirname,'..');
const serial=fs.readFileSync(path.join(root,'lib','serial-bridge.js'),'utf8');
const audio=fs.readFileSync(path.join(root,'public','audio-manager.js'),'utf8');
const firmware=fs.readFileSync(path.join(root,'arduino','Lightning_LED_Controller_Nano','Lightning_LED_Controller_Nano.ino'),'utf8');
const app=fs.readFileSync(path.join(root,'public','app.js'),'utf8');
const style=fs.readFileSync(path.join(root,'public','style.css'),'utf8');
const config=JSON.parse(fs.readFileSync(path.join(root,'config.json'),'utf8'));
const main=fs.readFileSync(path.join(root,'main.js'),'utf8');

assert(serial.includes('this.queue=[]'), 'serial bridge must queue commands');
assert(serial.includes('commandIntervalMs||12'), 'serial bridge must pace commands for Nano RX buffer');
assert(serial.includes('this.queue.length=0;this.generation++'), 'mode changes must discard stale LED commands');
assert(audio.includes('const token=++this.fadeToken'), 'audio fades must invalidate older transitions');
assert(audio.includes('if(token!==this.fadeToken)return'), 'stale audio callbacks must stop immediately');
assert(/strip\.Color\(255, 255, 255\)/.test(firmware), 'confirmation button must be static white');
assert(!/rainbowColor\(strip,[^\n]+confirmPosition/.test(firmware), 'confirmation button must not be redrawn forever');
assert(/MODE IDLE[\s\S]+confirmPosition\[0\] = confirmPosition\[1\] = 0/.test(firmware), 'idle mode must clear confirmation LEDs');
assert.equal(config.controlOrientation,'auto','control orientation must default to automatic detection');
assert(app.includes("innerHeight>innerWidth?'portrait':'landscape'"),'automatic orientation must use the actual window dimensions');
assert(app.includes("if(role==='control')app.innerHTML=`<section class=\"screen control-game\""),'control display must use the reduced in-game layout');
assert(style.includes('body.portrait .mode-grid{grid-template-columns:1fr'),'portrait mode list must use a single scrollable column');
assert(/setPhase\('gameover'\);phaseTimer=setTimeout\(\(\)=>\{setPhase\('results'\);phaseTimer=setTimeout\(\(\)=>\{setPhase\('leaderboard'\)/.test(app),'session end must show game over, results and then leaderboard');
assert.equal(config.strivex.enabled,true,'StriveX must be enabled in the production configuration');
assert.equal(config.strivex.transport,'websocket','updated Gateway must use the gameserver WebSocket adapter');
assert.equal(config.strivex.wsPort,4200,'Lightning and Gateway must agree on WebSocket port 4200');
assert.equal(config.offline.enabled,false,'free/offline sessions must be disabled');
assert.equal(config.rfid.enabled,false,'RFID must be owned by StriveX Gateway, not Lightning');
assert(!app.includes('data-action="skipCard"'),'no-card bypass must not be rendered');
assert(app.includes("phase:gatewayMode?'locked':'idle'"),'Gateway mode must boot into the locked screen');
assert(app.includes('finishGatewaySession'),'paid session must have a single finalization path');
assert(main.includes("require('./lib/strivex-session')"),'Electron main process must load the Gateway WebSocket session module');
console.log('Audio, serial pacing and static confirmation guards passed.');
